modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]] #mandatory
modId="thatched" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Thatched" #mandatory
credits="Thanks to Telepathicgrunt for guiding me into the way of structure mods" #optional
authors="lilypuree" #optional
description='''
Villages with thatched roofs from the decorative blocks mod
More thatch mod compat'''

[[dependencies.thatched]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[41,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.thatched]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.thatched]]
modId="decorative_blocks"
mandatory=true
versionRange="[3.0.0,)"
ordering="NONE"
side="BOTH"